# ====================================================================
# 🐳 DOCKER COMPOSE UNIFICADO - DIGIURBAN SYSTEM
# ====================================================================
# Container único com Frontend + Backend + Nginx
# ====================================================================

services:
  digiurban:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digiurban-unified
    restart: unless-stopped
    ports:
      - "3020:80"
    environment:
      - NODE_ENV=production
      - PORT=3021
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# ================================================================
# VOLUMES PERSISTENTES
# ================================================================
volumes:
  app_data:
    driver: local
  app_logs:
    driver: local